### PR TITLE
Feature07

### LINKED ISSUE #16: 2001 Weather requires money to aquire
this api costs too many moners for us to afford. change it to the weather the day before yesterday pls.

### PR DESCRIPTION
**Pull request by liammuir**
Renamed 2001 weather to brazil weather

Fixes #16

### CODE REVIEW

**Comment by liammuir** [comment]
Based off of feature06, merge 06 first

**Comment by liammuir** [comment]
how would I do this in the future?

**Review by davidtollefson — CHANGES_REQUESTED** [review]
Looks like a lot of the code in this PR is in the last PR.

Please merge the previous PR to main.

Then rebase this new PR from the update main, or merge main into this PR, so that it only reflects the changes made since the last one. Otherwise, we're committing the same changes twice, and will prevent the Issue - Branch - PR system from working at all.

**Comment by liammuir** [comment]
cool

**Pull request closed without merging**
